/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct param_int {
	int x;
	int y;
};
typedef struct param_int param_int;

#define CAL_PROG 0x31111111
#define CAL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULATE_ADD 1
extern  int * calculate_add_1(param_int *, CLIENT *);
extern  int * calculate_add_1_svc(param_int *, struct svc_req *);
#define CALCULATE_SUB 2
extern  int * calculate_sub_1(param_int *, CLIENT *);
extern  int * calculate_sub_1_svc(param_int *, struct svc_req *);
#define CALCULATE_MUL 3
extern  int * calculate_mul_1(param_int *, CLIENT *);
extern  int * calculate_mul_1_svc(param_int *, struct svc_req *);
#define CALCULATE_DIV 4
extern  int * calculate_div_1(param_int *, CLIENT *);
extern  int * calculate_div_1_svc(param_int *, struct svc_req *);
#define CALCULATE_POW 5
extern  int * calculate_pow_1(param_int *, CLIENT *);
extern  int * calculate_pow_1_svc(param_int *, struct svc_req *);
extern int cal_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULATE_ADD 1
extern  int * calculate_add_1();
extern  int * calculate_add_1_svc();
#define CALCULATE_SUB 2
extern  int * calculate_sub_1();
extern  int * calculate_sub_1_svc();
#define CALCULATE_MUL 3
extern  int * calculate_mul_1();
extern  int * calculate_mul_1_svc();
#define CALCULATE_DIV 4
extern  int * calculate_div_1();
extern  int * calculate_div_1_svc();
#define CALCULATE_POW 5
extern  int * calculate_pow_1();
extern  int * calculate_pow_1_svc();
extern int cal_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_param_int (XDR *, param_int*);

#else /* K&R C */
extern bool_t xdr_param_int ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
