/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"

int *
calculate_add_1_svc(param_int *argp, struct svc_req *rqstp)
{
	static int  result;

	int tmp = 0;
	tmp += argp->x;
	tmp += argp->y;
	result = tmp;

	return &result;
}

int *
calculate_sub_1_svc(param_int *argp, struct svc_req *rqstp)
{
	static int  result;

	int tmp = argp->x;
	tmp -= argp->y;
	result = tmp;

	return &result;
}

int *
calculate_mul_1_svc(param_int *argp, struct svc_req *rqstp)
{
	static int  result;

	int tmp = argp->x;
	tmp *= argp->y;
	result = tmp;

	return &result;
}

int *
calculate_div_1_svc(param_int *argp, struct svc_req *rqstp)
{
	static int  result;

	int tmp = argp->x;
	tmp /= argp->y;
	result = tmp;

	return &result;
}

int *
calculate_pow_1_svc(param_int *argp, struct svc_req *rqstp)
{
	static int  result;

	int i;
	int tmp = argp->x;
	for (i=1; i<argp->y; i++) {
		tmp = tmp * argp->x;
	}
	result = tmp;

	return &result;
}
